//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: RecentLogs.proto

// This file contains protocol buffers that are used for Online BalancerDecision history
// To be used as Ring Buffer payload

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalancerDecision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialFunctionCosts *string  `protobuf:"bytes,1,req,name=initial_function_costs,json=initialFunctionCosts" json:"initial_function_costs,omitempty"`
	FinalFunctionCosts   *string  `protobuf:"bytes,2,req,name=final_function_costs,json=finalFunctionCosts" json:"final_function_costs,omitempty"`
	InitTotalCost        *float64 `protobuf:"fixed64,3,req,name=init_total_cost,json=initTotalCost" json:"init_total_cost,omitempty"`
	ComputedTotalCost    *float64 `protobuf:"fixed64,4,req,name=computed_total_cost,json=computedTotalCost" json:"computed_total_cost,omitempty"`
	ComputedSteps        *uint64  `protobuf:"varint,5,req,name=computed_steps,json=computedSteps" json:"computed_steps,omitempty"`
	RegionPlans          []string `protobuf:"bytes,6,rep,name=region_plans,json=regionPlans" json:"region_plans,omitempty"`
}

func (x *BalancerDecision) Reset() {
	*x = BalancerDecision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RecentLogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalancerDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerDecision) ProtoMessage() {}

func (x *BalancerDecision) ProtoReflect() protoreflect.Message {
	mi := &file_RecentLogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerDecision.ProtoReflect.Descriptor instead.
func (*BalancerDecision) Descriptor() ([]byte, []int) {
	return file_RecentLogs_proto_rawDescGZIP(), []int{0}
}

func (x *BalancerDecision) GetInitialFunctionCosts() string {
	if x != nil && x.InitialFunctionCosts != nil {
		return *x.InitialFunctionCosts
	}
	return ""
}

func (x *BalancerDecision) GetFinalFunctionCosts() string {
	if x != nil && x.FinalFunctionCosts != nil {
		return *x.FinalFunctionCosts
	}
	return ""
}

func (x *BalancerDecision) GetInitTotalCost() float64 {
	if x != nil && x.InitTotalCost != nil {
		return *x.InitTotalCost
	}
	return 0
}

func (x *BalancerDecision) GetComputedTotalCost() float64 {
	if x != nil && x.ComputedTotalCost != nil {
		return *x.ComputedTotalCost
	}
	return 0
}

func (x *BalancerDecision) GetComputedSteps() uint64 {
	if x != nil && x.ComputedSteps != nil {
		return *x.ComputedSteps
	}
	return 0
}

func (x *BalancerDecision) GetRegionPlans() []string {
	if x != nil {
		return x.RegionPlans
	}
	return nil
}

type BalancerRejection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason       *string  `protobuf:"bytes,1,req,name=reason" json:"reason,omitempty"`
	CostFuncInfo []string `protobuf:"bytes,2,rep,name=cost_func_info,json=costFuncInfo" json:"cost_func_info,omitempty"`
}

func (x *BalancerRejection) Reset() {
	*x = BalancerRejection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RecentLogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalancerRejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerRejection) ProtoMessage() {}

func (x *BalancerRejection) ProtoReflect() protoreflect.Message {
	mi := &file_RecentLogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerRejection.ProtoReflect.Descriptor instead.
func (*BalancerRejection) Descriptor() ([]byte, []int) {
	return file_RecentLogs_proto_rawDescGZIP(), []int{1}
}

func (x *BalancerRejection) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *BalancerRejection) GetCostFuncInfo() []string {
	if x != nil {
		return x.CostFuncInfo
	}
	return nil
}

var File_RecentLogs_proto protoreflect.FileDescriptor

var file_RecentLogs_proto_rawDesc = []byte{
	0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9c, 0x02, 0x0a, 0x10, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x16, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x63, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x14, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74,
	0x73, 0x12, 0x30, 0x0a, 0x14, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x12, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x73, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0d, 0x69, 0x6e,
	0x69, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x63,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x01, 0x52, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x05, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x64, 0x53, 0x74, 0x65,
	0x70, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x6e, 0x73, 0x22, 0x51, 0x0a, 0x11, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x73, 0x74,
	0x46, 0x75, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x44, 0x0a, 0x31, 0x6f, 0x72, 0x67, 0x2e,
	0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0a, 0x52,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x48, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_RecentLogs_proto_rawDescOnce sync.Once
	file_RecentLogs_proto_rawDescData = file_RecentLogs_proto_rawDesc
)

func file_RecentLogs_proto_rawDescGZIP() []byte {
	file_RecentLogs_proto_rawDescOnce.Do(func() {
		file_RecentLogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_RecentLogs_proto_rawDescData)
	})
	return file_RecentLogs_proto_rawDescData
}

var file_RecentLogs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_RecentLogs_proto_goTypes = []interface{}{
	(*BalancerDecision)(nil),  // 0: pb.BalancerDecision
	(*BalancerRejection)(nil), // 1: pb.BalancerRejection
}
var file_RecentLogs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RecentLogs_proto_init() }
func file_RecentLogs_proto_init() {
	if File_RecentLogs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RecentLogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalancerDecision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RecentLogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalancerRejection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RecentLogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RecentLogs_proto_goTypes,
		DependencyIndexes: file_RecentLogs_proto_depIdxs,
		MessageInfos:      file_RecentLogs_proto_msgTypes,
	}.Build()
	File_RecentLogs_proto = out.File
	file_RecentLogs_proto_rawDesc = nil
	file_RecentLogs_proto_goTypes = nil
	file_RecentLogs_proto_depIdxs = nil
}
