//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: Registry.proto

// The protos for ConnectionRegistry.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* Request and response to get the clusterID for this cluster
type GetClusterIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetClusterIdRequest) Reset() {
	*x = GetClusterIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClusterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterIdRequest) ProtoMessage() {}

func (x *GetClusterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterIdRequest.ProtoReflect.Descriptor instead.
func (*GetClusterIdRequest) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{0}
}

type GetClusterIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Not set if cluster ID could not be determined.
	ClusterId *string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
}

func (x *GetClusterIdResponse) Reset() {
	*x = GetClusterIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClusterIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterIdResponse) ProtoMessage() {}

func (x *GetClusterIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterIdResponse.ProtoReflect.Descriptor instead.
func (*GetClusterIdResponse) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{1}
}

func (x *GetClusterIdResponse) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

//* Request and response to get the currently active master name for this cluster
type GetActiveMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetActiveMasterRequest) Reset() {
	*x = GetActiveMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveMasterRequest) ProtoMessage() {}

func (x *GetActiveMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveMasterRequest.ProtoReflect.Descriptor instead.
func (*GetActiveMasterRequest) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{2}
}

type GetActiveMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Not set if an active master could not be determined.
	ServerName *ServerName `protobuf:"bytes,1,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (x *GetActiveMasterResponse) Reset() {
	*x = GetActiveMasterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveMasterResponse) ProtoMessage() {}

func (x *GetActiveMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveMasterResponse.ProtoReflect.Descriptor instead.
func (*GetActiveMasterResponse) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetActiveMasterResponse) GetServerName() *ServerName {
	if x != nil {
		return x.ServerName
	}
	return nil
}

//* Request and response to get the current list of all registers master servers
// Deprecated: Do not use.
type GetMastersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMastersRequest) Reset() {
	*x = GetMastersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMastersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMastersRequest) ProtoMessage() {}

func (x *GetMastersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMastersRequest.ProtoReflect.Descriptor instead.
func (*GetMastersRequest) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Do not use.
type GetMastersResponseEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName *ServerName `protobuf:"bytes,1,req,name=server_name,json=serverName" json:"server_name,omitempty"`
	IsActive   *bool       `protobuf:"varint,2,req,name=is_active,json=isActive" json:"is_active,omitempty"`
}

func (x *GetMastersResponseEntry) Reset() {
	*x = GetMastersResponseEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMastersResponseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMastersResponseEntry) ProtoMessage() {}

func (x *GetMastersResponseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMastersResponseEntry.ProtoReflect.Descriptor instead.
func (*GetMastersResponseEntry) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetMastersResponseEntry) GetServerName() *ServerName {
	if x != nil {
		return x.ServerName
	}
	return nil
}

func (x *GetMastersResponseEntry) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// Deprecated: Do not use.
type GetMastersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterServers []*GetMastersResponseEntry `protobuf:"bytes,1,rep,name=master_servers,json=masterServers" json:"master_servers,omitempty"`
}

func (x *GetMastersResponse) Reset() {
	*x = GetMastersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMastersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMastersResponse) ProtoMessage() {}

func (x *GetMastersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMastersResponse.ProtoReflect.Descriptor instead.
func (*GetMastersResponse) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetMastersResponse) GetMasterServers() []*GetMastersResponseEntry {
	if x != nil {
		return x.MasterServers
	}
	return nil
}

//* Request and response to get the current list of meta region locations
type GetMetaRegionLocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMetaRegionLocationsRequest) Reset() {
	*x = GetMetaRegionLocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaRegionLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaRegionLocationsRequest) ProtoMessage() {}

func (x *GetMetaRegionLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaRegionLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetMetaRegionLocationsRequest) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{7}
}

type GetMetaRegionLocationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Not set if meta region locations could not be determined.
	MetaLocations []*RegionLocation `protobuf:"bytes,1,rep,name=meta_locations,json=metaLocations" json:"meta_locations,omitempty"`
}

func (x *GetMetaRegionLocationsResponse) Reset() {
	*x = GetMetaRegionLocationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaRegionLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaRegionLocationsResponse) ProtoMessage() {}

func (x *GetMetaRegionLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaRegionLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetMetaRegionLocationsResponse) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetMetaRegionLocationsResponse) GetMetaLocations() []*RegionLocation {
	if x != nil {
		return x.MetaLocations
	}
	return nil
}

//* Request and response to get the nodes which could be used to as ClientMetaService
type GetBootstrapNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBootstrapNodesRequest) Reset() {
	*x = GetBootstrapNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBootstrapNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapNodesRequest) ProtoMessage() {}

func (x *GetBootstrapNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapNodesRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapNodesRequest) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{9}
}

type GetBootstrapNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerName []*ServerName `protobuf:"bytes,1,rep,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (x *GetBootstrapNodesResponse) Reset() {
	*x = GetBootstrapNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Registry_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBootstrapNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapNodesResponse) ProtoMessage() {}

func (x *GetBootstrapNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Registry_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapNodesResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapNodesResponse) Descriptor() ([]byte, []int) {
	return file_Registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetBootstrapNodesResponse) GetServerName() []*ServerName {
	if x != nil {
		return x.ServerName
	}
	return nil
}

var File_Registry_proto protoreflect.FileDescriptor

var file_Registry_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x48, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x3a, 0x02, 0x18, 0x01, 0x22, 0x6b,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x3a, 0x02, 0x18, 0x01, 0x22, 0x5c, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x0e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x3a, 0x02, 0x18, 0x01, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x1e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0e,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x32, 0x97, 0x03, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x03, 0x88, 0x02, 0x01, 0x12, 0x5f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4b, 0x0a, 0x31, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x48, 0x01, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_Registry_proto_rawDescOnce sync.Once
	file_Registry_proto_rawDescData = file_Registry_proto_rawDesc
)

func file_Registry_proto_rawDescGZIP() []byte {
	file_Registry_proto_rawDescOnce.Do(func() {
		file_Registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_Registry_proto_rawDescData)
	})
	return file_Registry_proto_rawDescData
}

var file_Registry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Registry_proto_goTypes = []interface{}{
	(*GetClusterIdRequest)(nil),            // 0: pb.GetClusterIdRequest
	(*GetClusterIdResponse)(nil),           // 1: pb.GetClusterIdResponse
	(*GetActiveMasterRequest)(nil),         // 2: pb.GetActiveMasterRequest
	(*GetActiveMasterResponse)(nil),        // 3: pb.GetActiveMasterResponse
	(*GetMastersRequest)(nil),              // 4: pb.GetMastersRequest
	(*GetMastersResponseEntry)(nil),        // 5: pb.GetMastersResponseEntry
	(*GetMastersResponse)(nil),             // 6: pb.GetMastersResponse
	(*GetMetaRegionLocationsRequest)(nil),  // 7: pb.GetMetaRegionLocationsRequest
	(*GetMetaRegionLocationsResponse)(nil), // 8: pb.GetMetaRegionLocationsResponse
	(*GetBootstrapNodesRequest)(nil),       // 9: pb.GetBootstrapNodesRequest
	(*GetBootstrapNodesResponse)(nil),      // 10: pb.GetBootstrapNodesResponse
	(*ServerName)(nil),                     // 11: pb.ServerName
	(*RegionLocation)(nil),                 // 12: pb.RegionLocation
}
var file_Registry_proto_depIdxs = []int32{
	11, // 0: pb.GetActiveMasterResponse.server_name:type_name -> pb.ServerName
	11, // 1: pb.GetMastersResponseEntry.server_name:type_name -> pb.ServerName
	5,  // 2: pb.GetMastersResponse.master_servers:type_name -> pb.GetMastersResponseEntry
	12, // 3: pb.GetMetaRegionLocationsResponse.meta_locations:type_name -> pb.RegionLocation
	11, // 4: pb.GetBootstrapNodesResponse.server_name:type_name -> pb.ServerName
	0,  // 5: pb.ClientMetaService.GetClusterId:input_type -> pb.GetClusterIdRequest
	2,  // 6: pb.ClientMetaService.GetActiveMaster:input_type -> pb.GetActiveMasterRequest
	4,  // 7: pb.ClientMetaService.GetMasters:input_type -> pb.GetMastersRequest
	7,  // 8: pb.ClientMetaService.GetMetaRegionLocations:input_type -> pb.GetMetaRegionLocationsRequest
	9,  // 9: pb.ClientMetaService.GetBootstrapNodes:input_type -> pb.GetBootstrapNodesRequest
	1,  // 10: pb.ClientMetaService.GetClusterId:output_type -> pb.GetClusterIdResponse
	3,  // 11: pb.ClientMetaService.GetActiveMaster:output_type -> pb.GetActiveMasterResponse
	6,  // 12: pb.ClientMetaService.GetMasters:output_type -> pb.GetMastersResponse
	8,  // 13: pb.ClientMetaService.GetMetaRegionLocations:output_type -> pb.GetMetaRegionLocationsResponse
	10, // 14: pb.ClientMetaService.GetBootstrapNodes:output_type -> pb.GetBootstrapNodesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_Registry_proto_init() }
func file_Registry_proto_init() {
	if File_Registry_proto != nil {
		return
	}
	file_HBase_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClusterIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClusterIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveMasterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMastersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMastersResponseEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMastersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaRegionLocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaRegionLocationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBootstrapNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Registry_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBootstrapNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Registry_proto_goTypes,
		DependencyIndexes: file_Registry_proto_depIdxs,
		MessageInfos:      file_Registry_proto_msgTypes,
	}.Build()
	File_Registry_proto = out.File
	file_Registry_proto_rawDesc = nil
	file_Registry_proto_goTypes = nil
	file_Registry_proto_depIdxs = nil
}
