//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: RegionServerStatus.proto

// This file contains protocol buffers that are used for RegionServerStatusProtocol.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionStateTransition_TransitionCode int32

const (
	RegionStateTransition_OPENED      RegionStateTransition_TransitionCode = 0
	RegionStateTransition_FAILED_OPEN RegionStateTransition_TransitionCode = 1
	//* No failed_close, in which case region server will abort
	RegionStateTransition_CLOSED RegionStateTransition_TransitionCode = 2
	//* Ask master for ok to split/merge region(s)
	RegionStateTransition_READY_TO_SPLIT RegionStateTransition_TransitionCode = 3
	RegionStateTransition_READY_TO_MERGE RegionStateTransition_TransitionCode = 4
	//* We used to have PONR enums for split and merge in here occupying
	//positions 5 and 6 but they have since been removed. Do not reuse these
	//indices
	RegionStateTransition_SPLIT          RegionStateTransition_TransitionCode = 7
	RegionStateTransition_MERGED         RegionStateTransition_TransitionCode = 8
	RegionStateTransition_SPLIT_REVERTED RegionStateTransition_TransitionCode = 9
	RegionStateTransition_MERGE_REVERTED RegionStateTransition_TransitionCode = 10
)

// Enum value maps for RegionStateTransition_TransitionCode.
var (
	RegionStateTransition_TransitionCode_name = map[int32]string{
		0:  "OPENED",
		1:  "FAILED_OPEN",
		2:  "CLOSED",
		3:  "READY_TO_SPLIT",
		4:  "READY_TO_MERGE",
		7:  "SPLIT",
		8:  "MERGED",
		9:  "SPLIT_REVERTED",
		10: "MERGE_REVERTED",
	}
	RegionStateTransition_TransitionCode_value = map[string]int32{
		"OPENED":         0,
		"FAILED_OPEN":    1,
		"CLOSED":         2,
		"READY_TO_SPLIT": 3,
		"READY_TO_MERGE": 4,
		"SPLIT":          7,
		"MERGED":         8,
		"SPLIT_REVERTED": 9,
		"MERGE_REVERTED": 10,
	}
)

func (x RegionStateTransition_TransitionCode) Enum() *RegionStateTransition_TransitionCode {
	p := new(RegionStateTransition_TransitionCode)
	*p = x
	return p
}

func (x RegionStateTransition_TransitionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionStateTransition_TransitionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_RegionServerStatus_proto_enumTypes[0].Descriptor()
}

func (RegionStateTransition_TransitionCode) Type() protoreflect.EnumType {
	return &file_RegionServerStatus_proto_enumTypes[0]
}

func (x RegionStateTransition_TransitionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RegionStateTransition_TransitionCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RegionStateTransition_TransitionCode(num)
	return nil
}

// Deprecated: Use RegionStateTransition_TransitionCode.Descriptor instead.
func (RegionStateTransition_TransitionCode) EnumDescriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{8, 0}
}

type RemoteProcedureResult_Status int32

const (
	RemoteProcedureResult_SUCCESS RemoteProcedureResult_Status = 1
	RemoteProcedureResult_ERROR   RemoteProcedureResult_Status = 2
)

// Enum value maps for RemoteProcedureResult_Status.
var (
	RemoteProcedureResult_Status_name = map[int32]string{
		1: "SUCCESS",
		2: "ERROR",
	}
	RemoteProcedureResult_Status_value = map[string]int32{
		"SUCCESS": 1,
		"ERROR":   2,
	}
)

func (x RemoteProcedureResult_Status) Enum() *RemoteProcedureResult_Status {
	p := new(RemoteProcedureResult_Status)
	*p = x
	return p
}

func (x RemoteProcedureResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteProcedureResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_RegionServerStatus_proto_enumTypes[1].Descriptor()
}

func (RemoteProcedureResult_Status) Type() protoreflect.EnumType {
	return &file_RegionServerStatus_proto_enumTypes[1]
}

func (x RemoteProcedureResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RemoteProcedureResult_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RemoteProcedureResult_Status(num)
	return nil
}

// Deprecated: Use RemoteProcedureResult_Status.Descriptor instead.
func (RemoteProcedureResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{14, 0}
}

type RegionServerStartupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Port number this regionserver is up on
	Port *uint32 `protobuf:"varint,1,req,name=port" json:"port,omitempty"`
	//* This servers' startcode
	ServerStartCode *uint64 `protobuf:"varint,2,req,name=server_start_code,json=serverStartCode" json:"server_start_code,omitempty"`
	//* Current time of the region server in ms
	ServerCurrentTime *uint64 `protobuf:"varint,3,req,name=server_current_time,json=serverCurrentTime" json:"server_current_time,omitempty"`
	//* hostname for region server, optional
	UseThisHostnameInstead *string `protobuf:"bytes,4,opt,name=use_this_hostname_instead,json=useThisHostnameInstead" json:"use_this_hostname_instead,omitempty"`
}

func (x *RegionServerStartupRequest) Reset() {
	*x = RegionServerStartupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionServerStartupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionServerStartupRequest) ProtoMessage() {}

func (x *RegionServerStartupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionServerStartupRequest.ProtoReflect.Descriptor instead.
func (*RegionServerStartupRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{0}
}

func (x *RegionServerStartupRequest) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *RegionServerStartupRequest) GetServerStartCode() uint64 {
	if x != nil && x.ServerStartCode != nil {
		return *x.ServerStartCode
	}
	return 0
}

func (x *RegionServerStartupRequest) GetServerCurrentTime() uint64 {
	if x != nil && x.ServerCurrentTime != nil {
		return *x.ServerCurrentTime
	}
	return 0
}

func (x *RegionServerStartupRequest) GetUseThisHostnameInstead() string {
	if x != nil && x.UseThisHostnameInstead != nil {
		return *x.UseThisHostnameInstead
	}
	return ""
}

type RegionServerStartupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Configuration for the regionserver to use: e.g. filesystem,
	// hbase rootdir, the hostname to use creating the RegionServer ServerName,
	// etc
	MapEntries []*NameStringPair `protobuf:"bytes,1,rep,name=map_entries,json=mapEntries" json:"map_entries,omitempty"`
}

func (x *RegionServerStartupResponse) Reset() {
	*x = RegionServerStartupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionServerStartupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionServerStartupResponse) ProtoMessage() {}

func (x *RegionServerStartupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionServerStartupResponse.ProtoReflect.Descriptor instead.
func (*RegionServerStartupResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{1}
}

func (x *RegionServerStartupResponse) GetMapEntries() []*NameStringPair {
	if x != nil {
		return x.MapEntries
	}
	return nil
}

type RegionServerReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *ServerName `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	//* load the server is under
	Load *ServerLoad `protobuf:"bytes,2,opt,name=load" json:"load,omitempty"`
}

func (x *RegionServerReportRequest) Reset() {
	*x = RegionServerReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionServerReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionServerReportRequest) ProtoMessage() {}

func (x *RegionServerReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionServerReportRequest.ProtoReflect.Descriptor instead.
func (*RegionServerReportRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{2}
}

func (x *RegionServerReportRequest) GetServer() *ServerName {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *RegionServerReportRequest) GetLoad() *ServerLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

type RegionServerReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionServerReportResponse) Reset() {
	*x = RegionServerReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionServerReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionServerReportResponse) ProtoMessage() {}

func (x *RegionServerReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionServerReportResponse.ProtoReflect.Descriptor instead.
func (*RegionServerReportResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{3}
}

type ReportRSFatalErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* name of the server experiencing the error
	Server *ServerName `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	//* informative text to expose in the master logs and UI
	ErrorMessage *string `protobuf:"bytes,2,req,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (x *ReportRSFatalErrorRequest) Reset() {
	*x = ReportRSFatalErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRSFatalErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRSFatalErrorRequest) ProtoMessage() {}

func (x *ReportRSFatalErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRSFatalErrorRequest.ProtoReflect.Descriptor instead.
func (*ReportRSFatalErrorRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{4}
}

func (x *ReportRSFatalErrorRequest) GetServer() *ServerName {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ReportRSFatalErrorRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type ReportRSFatalErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportRSFatalErrorResponse) Reset() {
	*x = ReportRSFatalErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRSFatalErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRSFatalErrorResponse) ProtoMessage() {}

func (x *ReportRSFatalErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRSFatalErrorResponse.ProtoReflect.Descriptor instead.
func (*ReportRSFatalErrorResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{5}
}

type GetLastFlushedSequenceIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* region name
	RegionName []byte `protobuf:"bytes,1,req,name=region_name,json=regionName" json:"region_name,omitempty"`
}

func (x *GetLastFlushedSequenceIdRequest) Reset() {
	*x = GetLastFlushedSequenceIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastFlushedSequenceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastFlushedSequenceIdRequest) ProtoMessage() {}

func (x *GetLastFlushedSequenceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastFlushedSequenceIdRequest.ProtoReflect.Descriptor instead.
func (*GetLastFlushedSequenceIdRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastFlushedSequenceIdRequest) GetRegionName() []byte {
	if x != nil {
		return x.RegionName
	}
	return nil
}

type GetLastFlushedSequenceIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* the last WAL sequence id flushed from MemStore to HFile for the region
	LastFlushedSequenceId *uint64 `protobuf:"varint,1,req,name=last_flushed_sequence_id,json=lastFlushedSequenceId" json:"last_flushed_sequence_id,omitempty"`
	//* the last WAL sequence id flushed from MemStore to HFile for stores of the region
	StoreLastFlushedSequenceId []*StoreSequenceId `protobuf:"bytes,2,rep,name=store_last_flushed_sequence_id,json=storeLastFlushedSequenceId" json:"store_last_flushed_sequence_id,omitempty"`
}

func (x *GetLastFlushedSequenceIdResponse) Reset() {
	*x = GetLastFlushedSequenceIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastFlushedSequenceIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastFlushedSequenceIdResponse) ProtoMessage() {}

func (x *GetLastFlushedSequenceIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastFlushedSequenceIdResponse.ProtoReflect.Descriptor instead.
func (*GetLastFlushedSequenceIdResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastFlushedSequenceIdResponse) GetLastFlushedSequenceId() uint64 {
	if x != nil && x.LastFlushedSequenceId != nil {
		return *x.LastFlushedSequenceId
	}
	return 0
}

func (x *GetLastFlushedSequenceIdResponse) GetStoreLastFlushedSequenceId() []*StoreSequenceId {
	if x != nil {
		return x.StoreLastFlushedSequenceId
	}
	return nil
}

type RegionStateTransition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransitionCode *RegionStateTransition_TransitionCode `protobuf:"varint,1,req,name=transition_code,json=transitionCode,enum=pb.RegionStateTransition_TransitionCode" json:"transition_code,omitempty"`
	//* Mutliple regions are involved during merging/splitting
	RegionInfo []*RegionInfo `protobuf:"bytes,2,rep,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	//* For newly opened region, the open seq num is needed
	OpenSeqNum *uint64 `protobuf:"varint,3,opt,name=open_seq_num,json=openSeqNum" json:"open_seq_num,omitempty"`
	ProcId     []int64 `protobuf:"varint,4,rep,name=proc_id,json=procId" json:"proc_id,omitempty"`
}

func (x *RegionStateTransition) Reset() {
	*x = RegionStateTransition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionStateTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStateTransition) ProtoMessage() {}

func (x *RegionStateTransition) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStateTransition.ProtoReflect.Descriptor instead.
func (*RegionStateTransition) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{8}
}

func (x *RegionStateTransition) GetTransitionCode() RegionStateTransition_TransitionCode {
	if x != nil && x.TransitionCode != nil {
		return *x.TransitionCode
	}
	return RegionStateTransition_OPENED
}

func (x *RegionStateTransition) GetRegionInfo() []*RegionInfo {
	if x != nil {
		return x.RegionInfo
	}
	return nil
}

func (x *RegionStateTransition) GetOpenSeqNum() uint64 {
	if x != nil && x.OpenSeqNum != nil {
		return *x.OpenSeqNum
	}
	return 0
}

func (x *RegionStateTransition) GetProcId() []int64 {
	if x != nil {
		return x.ProcId
	}
	return nil
}

type ReportRegionStateTransitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* This region server's server name
	Server     *ServerName              `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Transition []*RegionStateTransition `protobuf:"bytes,2,rep,name=transition" json:"transition,omitempty"`
}

func (x *ReportRegionStateTransitionRequest) Reset() {
	*x = ReportRegionStateTransitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRegionStateTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRegionStateTransitionRequest) ProtoMessage() {}

func (x *ReportRegionStateTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRegionStateTransitionRequest.ProtoReflect.Descriptor instead.
func (*ReportRegionStateTransitionRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{9}
}

func (x *ReportRegionStateTransitionRequest) GetServer() *ServerName {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ReportRegionStateTransitionRequest) GetTransition() []*RegionStateTransition {
	if x != nil {
		return x.Transition
	}
	return nil
}

type ReportRegionStateTransitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//* Error message if failed to update the region state
	ErrorMessage *string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (x *ReportRegionStateTransitionResponse) Reset() {
	*x = ReportRegionStateTransitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRegionStateTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRegionStateTransitionResponse) ProtoMessage() {}

func (x *ReportRegionStateTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRegionStateTransitionResponse.ProtoReflect.Descriptor instead.
func (*ReportRegionStateTransitionResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{10}
}

func (x *ReportRegionStateTransitionResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RegionSpaceUse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionInfo *RegionInfo `protobuf:"bytes,1,opt,name=region_info,json=regionInfo" json:"region_info,omitempty"`  // A region identifier
	RegionSize *uint64     `protobuf:"varint,2,opt,name=region_size,json=regionSize" json:"region_size,omitempty"` // The size in bytes of the region
}

func (x *RegionSpaceUse) Reset() {
	*x = RegionSpaceUse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionSpaceUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpaceUse) ProtoMessage() {}

func (x *RegionSpaceUse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpaceUse.ProtoReflect.Descriptor instead.
func (*RegionSpaceUse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{11}
}

func (x *RegionSpaceUse) GetRegionInfo() *RegionInfo {
	if x != nil {
		return x.RegionInfo
	}
	return nil
}

func (x *RegionSpaceUse) GetRegionSize() uint64 {
	if x != nil && x.RegionSize != nil {
		return *x.RegionSize
	}
	return 0
}

//*
// Reports filesystem usage for regions.
type RegionSpaceUseReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceUse []*RegionSpaceUse `protobuf:"bytes,1,rep,name=space_use,json=spaceUse" json:"space_use,omitempty"`
}

func (x *RegionSpaceUseReportRequest) Reset() {
	*x = RegionSpaceUseReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionSpaceUseReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpaceUseReportRequest) ProtoMessage() {}

func (x *RegionSpaceUseReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpaceUseReportRequest.ProtoReflect.Descriptor instead.
func (*RegionSpaceUseReportRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{12}
}

func (x *RegionSpaceUseReportRequest) GetSpaceUse() []*RegionSpaceUse {
	if x != nil {
		return x.SpaceUse
	}
	return nil
}

type RegionSpaceUseReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionSpaceUseReportResponse) Reset() {
	*x = RegionSpaceUseReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionSpaceUseReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpaceUseReportResponse) ProtoMessage() {}

func (x *RegionSpaceUseReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpaceUseReportResponse.ProtoReflect.Descriptor instead.
func (*RegionSpaceUseReportResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{13}
}

type RemoteProcedureResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcId *uint64                       `protobuf:"varint,1,req,name=proc_id,json=procId" json:"proc_id,omitempty"`
	Status *RemoteProcedureResult_Status `protobuf:"varint,2,req,name=status,enum=pb.RemoteProcedureResult_Status" json:"status,omitempty"`
	Error  *ForeignExceptionMessage      `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (x *RemoteProcedureResult) Reset() {
	*x = RemoteProcedureResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteProcedureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteProcedureResult) ProtoMessage() {}

func (x *RemoteProcedureResult) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteProcedureResult.ProtoReflect.Descriptor instead.
func (*RemoteProcedureResult) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{14}
}

func (x *RemoteProcedureResult) GetProcId() uint64 {
	if x != nil && x.ProcId != nil {
		return *x.ProcId
	}
	return 0
}

func (x *RemoteProcedureResult) GetStatus() RemoteProcedureResult_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return RemoteProcedureResult_SUCCESS
}

func (x *RemoteProcedureResult) GetError() *ForeignExceptionMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReportProcedureDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*RemoteProcedureResult `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (x *ReportProcedureDoneRequest) Reset() {
	*x = ReportProcedureDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportProcedureDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcedureDoneRequest) ProtoMessage() {}

func (x *ReportProcedureDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcedureDoneRequest.ProtoReflect.Descriptor instead.
func (*ReportProcedureDoneRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{15}
}

func (x *ReportProcedureDoneRequest) GetResult() []*RemoteProcedureResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportProcedureDoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportProcedureDoneResponse) Reset() {
	*x = ReportProcedureDoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportProcedureDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProcedureDoneResponse) ProtoMessage() {}

func (x *ReportProcedureDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProcedureDoneResponse.ProtoReflect.Descriptor instead.
func (*ReportProcedureDoneResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{16}
}

type FileArchiveNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchivedFiles []*FileArchiveNotificationRequest_FileWithSize `protobuf:"bytes,1,rep,name=archived_files,json=archivedFiles" json:"archived_files,omitempty"`
}

func (x *FileArchiveNotificationRequest) Reset() {
	*x = FileArchiveNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileArchiveNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileArchiveNotificationRequest) ProtoMessage() {}

func (x *FileArchiveNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileArchiveNotificationRequest.ProtoReflect.Descriptor instead.
func (*FileArchiveNotificationRequest) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{17}
}

func (x *FileArchiveNotificationRequest) GetArchivedFiles() []*FileArchiveNotificationRequest_FileWithSize {
	if x != nil {
		return x.ArchivedFiles
	}
	return nil
}

type FileArchiveNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileArchiveNotificationResponse) Reset() {
	*x = FileArchiveNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileArchiveNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileArchiveNotificationResponse) ProtoMessage() {}

func (x *FileArchiveNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileArchiveNotificationResponse.ProtoReflect.Descriptor instead.
func (*FileArchiveNotificationResponse) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{18}
}

type FileArchiveNotificationRequest_FileWithSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName *TableName `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Name      *string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Size      *uint64    `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (x *FileArchiveNotificationRequest_FileWithSize) Reset() {
	*x = FileArchiveNotificationRequest_FileWithSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RegionServerStatus_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileArchiveNotificationRequest_FileWithSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileArchiveNotificationRequest_FileWithSize) ProtoMessage() {}

func (x *FileArchiveNotificationRequest_FileWithSize) ProtoReflect() protoreflect.Message {
	mi := &file_RegionServerStatus_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileArchiveNotificationRequest_FileWithSize.ProtoReflect.Descriptor instead.
func (*FileArchiveNotificationRequest_FileWithSize) Descriptor() ([]byte, []int) {
	return file_RegionServerStatus_proto_rawDescGZIP(), []int{17, 0}
}

func (x *FileArchiveNotificationRequest_FileWithSize) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *FileArchiveNotificationRequest_FileWithSize) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileArchiveNotificationRequest_FileWithSize) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_RegionServerStatus_proto protoreflect.FileDescriptor

var file_RegionServerStatus_proto_rawDesc = []byte{
	0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b,
	0x48, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x13, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x19, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x68, 0x69, 0x73,
	0x5f, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x65, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x75, 0x73, 0x65, 0x54, 0x68, 0x69, 0x73,
	0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x65, 0x61, 0x64, 0x22,
	0x52, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x67, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x1c, 0x0a, 0x1a,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x68, 0x0a, 0x19, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x53, 0x46, 0x61, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x53,
	0x46, 0x61, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x42, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x75,
	0x73, 0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x18, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x15, 0x6c,
	0x61, 0x73, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x57, 0x0a, 0x1e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x66, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x52, 0x1a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x75, 0x73,
	0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0xf9, 0x02,
	0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e,
	0x32, 0x28, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x63, 0x49, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x45,
	0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f,
	0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x54, 0x4f, 0x5f, 0x53,
	0x50, 0x4c, 0x49, 0x54, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f,
	0x54, 0x4f, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x50,
	0x4c, 0x49, 0x54, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x44, 0x10,
	0x08, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x56, 0x45, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x52,
	0x45, 0x56, 0x45, 0x52, 0x54, 0x45, 0x44, 0x10, 0x0a, 0x22, 0x87, 0x01, 0x0a, 0x22, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x23, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x62, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x55, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x4e, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x08, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x55, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x31, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x45, 0x78, 0x63, 0x65,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x4f, 0x0a, 0x1a, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x1e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x0e, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x0d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x1a, 0x64, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x21, 0x0a, 0x1f, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x06, 0x0a, 0x19, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x12, 0x1e,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x53,
	0x46, 0x61, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x53, 0x46, 0x61, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x53, 0x46, 0x61, 0x74, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x4c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x65, 0x64, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6e, 0x0a, 0x1b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x26, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x14, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x55, 0x73, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x55, 0x73, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x13, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x6f,
	0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x55, 0x0a, 0x31, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68,
	0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x18, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x48, 0x01, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_RegionServerStatus_proto_rawDescOnce sync.Once
	file_RegionServerStatus_proto_rawDescData = file_RegionServerStatus_proto_rawDesc
)

func file_RegionServerStatus_proto_rawDescGZIP() []byte {
	file_RegionServerStatus_proto_rawDescOnce.Do(func() {
		file_RegionServerStatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_RegionServerStatus_proto_rawDescData)
	})
	return file_RegionServerStatus_proto_rawDescData
}

var file_RegionServerStatus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_RegionServerStatus_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_RegionServerStatus_proto_goTypes = []interface{}{
	(RegionStateTransition_TransitionCode)(0),           // 0: pb.RegionStateTransition.TransitionCode
	(RemoteProcedureResult_Status)(0),                   // 1: pb.RemoteProcedureResult.Status
	(*RegionServerStartupRequest)(nil),                  // 2: pb.RegionServerStartupRequest
	(*RegionServerStartupResponse)(nil),                 // 3: pb.RegionServerStartupResponse
	(*RegionServerReportRequest)(nil),                   // 4: pb.RegionServerReportRequest
	(*RegionServerReportResponse)(nil),                  // 5: pb.RegionServerReportResponse
	(*ReportRSFatalErrorRequest)(nil),                   // 6: pb.ReportRSFatalErrorRequest
	(*ReportRSFatalErrorResponse)(nil),                  // 7: pb.ReportRSFatalErrorResponse
	(*GetLastFlushedSequenceIdRequest)(nil),             // 8: pb.GetLastFlushedSequenceIdRequest
	(*GetLastFlushedSequenceIdResponse)(nil),            // 9: pb.GetLastFlushedSequenceIdResponse
	(*RegionStateTransition)(nil),                       // 10: pb.RegionStateTransition
	(*ReportRegionStateTransitionRequest)(nil),          // 11: pb.ReportRegionStateTransitionRequest
	(*ReportRegionStateTransitionResponse)(nil),         // 12: pb.ReportRegionStateTransitionResponse
	(*RegionSpaceUse)(nil),                              // 13: pb.RegionSpaceUse
	(*RegionSpaceUseReportRequest)(nil),                 // 14: pb.RegionSpaceUseReportRequest
	(*RegionSpaceUseReportResponse)(nil),                // 15: pb.RegionSpaceUseReportResponse
	(*RemoteProcedureResult)(nil),                       // 16: pb.RemoteProcedureResult
	(*ReportProcedureDoneRequest)(nil),                  // 17: pb.ReportProcedureDoneRequest
	(*ReportProcedureDoneResponse)(nil),                 // 18: pb.ReportProcedureDoneResponse
	(*FileArchiveNotificationRequest)(nil),              // 19: pb.FileArchiveNotificationRequest
	(*FileArchiveNotificationResponse)(nil),             // 20: pb.FileArchiveNotificationResponse
	(*FileArchiveNotificationRequest_FileWithSize)(nil), // 21: pb.FileArchiveNotificationRequest.FileWithSize
	(*NameStringPair)(nil),                              // 22: pb.NameStringPair
	(*ServerName)(nil),                                  // 23: pb.ServerName
	(*ServerLoad)(nil),                                  // 24: pb.ServerLoad
	(*StoreSequenceId)(nil),                             // 25: pb.StoreSequenceId
	(*RegionInfo)(nil),                                  // 26: pb.RegionInfo
	(*ForeignExceptionMessage)(nil),                     // 27: pb.ForeignExceptionMessage
	(*TableName)(nil),                                   // 28: pb.TableName
}
var file_RegionServerStatus_proto_depIdxs = []int32{
	22, // 0: pb.RegionServerStartupResponse.map_entries:type_name -> pb.NameStringPair
	23, // 1: pb.RegionServerReportRequest.server:type_name -> pb.ServerName
	24, // 2: pb.RegionServerReportRequest.load:type_name -> pb.ServerLoad
	23, // 3: pb.ReportRSFatalErrorRequest.server:type_name -> pb.ServerName
	25, // 4: pb.GetLastFlushedSequenceIdResponse.store_last_flushed_sequence_id:type_name -> pb.StoreSequenceId
	0,  // 5: pb.RegionStateTransition.transition_code:type_name -> pb.RegionStateTransition.TransitionCode
	26, // 6: pb.RegionStateTransition.region_info:type_name -> pb.RegionInfo
	23, // 7: pb.ReportRegionStateTransitionRequest.server:type_name -> pb.ServerName
	10, // 8: pb.ReportRegionStateTransitionRequest.transition:type_name -> pb.RegionStateTransition
	26, // 9: pb.RegionSpaceUse.region_info:type_name -> pb.RegionInfo
	13, // 10: pb.RegionSpaceUseReportRequest.space_use:type_name -> pb.RegionSpaceUse
	1,  // 11: pb.RemoteProcedureResult.status:type_name -> pb.RemoteProcedureResult.Status
	27, // 12: pb.RemoteProcedureResult.error:type_name -> pb.ForeignExceptionMessage
	16, // 13: pb.ReportProcedureDoneRequest.result:type_name -> pb.RemoteProcedureResult
	21, // 14: pb.FileArchiveNotificationRequest.archived_files:type_name -> pb.FileArchiveNotificationRequest.FileWithSize
	28, // 15: pb.FileArchiveNotificationRequest.FileWithSize.table_name:type_name -> pb.TableName
	2,  // 16: pb.RegionServerStatusService.RegionServerStartup:input_type -> pb.RegionServerStartupRequest
	4,  // 17: pb.RegionServerStatusService.RegionServerReport:input_type -> pb.RegionServerReportRequest
	6,  // 18: pb.RegionServerStatusService.ReportRSFatalError:input_type -> pb.ReportRSFatalErrorRequest
	8,  // 19: pb.RegionServerStatusService.GetLastFlushedSequenceId:input_type -> pb.GetLastFlushedSequenceIdRequest
	11, // 20: pb.RegionServerStatusService.ReportRegionStateTransition:input_type -> pb.ReportRegionStateTransitionRequest
	14, // 21: pb.RegionServerStatusService.ReportRegionSpaceUse:input_type -> pb.RegionSpaceUseReportRequest
	17, // 22: pb.RegionServerStatusService.ReportProcedureDone:input_type -> pb.ReportProcedureDoneRequest
	19, // 23: pb.RegionServerStatusService.ReportFileArchival:input_type -> pb.FileArchiveNotificationRequest
	3,  // 24: pb.RegionServerStatusService.RegionServerStartup:output_type -> pb.RegionServerStartupResponse
	5,  // 25: pb.RegionServerStatusService.RegionServerReport:output_type -> pb.RegionServerReportResponse
	7,  // 26: pb.RegionServerStatusService.ReportRSFatalError:output_type -> pb.ReportRSFatalErrorResponse
	9,  // 27: pb.RegionServerStatusService.GetLastFlushedSequenceId:output_type -> pb.GetLastFlushedSequenceIdResponse
	12, // 28: pb.RegionServerStatusService.ReportRegionStateTransition:output_type -> pb.ReportRegionStateTransitionResponse
	15, // 29: pb.RegionServerStatusService.ReportRegionSpaceUse:output_type -> pb.RegionSpaceUseReportResponse
	18, // 30: pb.RegionServerStatusService.ReportProcedureDone:output_type -> pb.ReportProcedureDoneResponse
	20, // 31: pb.RegionServerStatusService.ReportFileArchival:output_type -> pb.FileArchiveNotificationResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_RegionServerStatus_proto_init() }
func file_RegionServerStatus_proto_init() {
	if File_RegionServerStatus_proto != nil {
		return
	}
	file_HBase_proto_init()
	file_ClusterStatus_proto_init()
	file_ErrorHandling_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_RegionServerStatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionServerStartupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionServerStartupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionServerReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionServerReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRSFatalErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRSFatalErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastFlushedSequenceIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastFlushedSequenceIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionStateTransition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRegionStateTransitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRegionStateTransitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionSpaceUse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionSpaceUseReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionSpaceUseReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteProcedureResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportProcedureDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportProcedureDoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileArchiveNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileArchiveNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RegionServerStatus_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileArchiveNotificationRequest_FileWithSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RegionServerStatus_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RegionServerStatus_proto_goTypes,
		DependencyIndexes: file_RegionServerStatus_proto_depIdxs,
		EnumInfos:         file_RegionServerStatus_proto_enumTypes,
		MessageInfos:      file_RegionServerStatus_proto_msgTypes,
	}.Build()
	File_RegionServerStatus_proto = out.File
	file_RegionServerStatus_proto_rawDesc = nil
	file_RegionServerStatus_proto_goTypes = nil
	file_RegionServerStatus_proto_depIdxs = nil
}
