//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: TooSlowLog.proto

// This file contains protocol buffers that are used for Online TooSlowLogs
// To be used as Ring Buffer payload

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SLOW_LOG is RPC call slow in nature whereas LARGE_LOG is RPC call quite large.
// Majority of times, slow logs are also large logs and hence, ALL is combination of
// both
type SlowLogPayload_Type int32

const (
	SlowLogPayload_SLOW_LOG  SlowLogPayload_Type = 0
	SlowLogPayload_LARGE_LOG SlowLogPayload_Type = 1
	SlowLogPayload_ALL       SlowLogPayload_Type = 2
)

// Enum value maps for SlowLogPayload_Type.
var (
	SlowLogPayload_Type_name = map[int32]string{
		0: "SLOW_LOG",
		1: "LARGE_LOG",
		2: "ALL",
	}
	SlowLogPayload_Type_value = map[string]int32{
		"SLOW_LOG":  0,
		"LARGE_LOG": 1,
		"ALL":       2,
	}
)

func (x SlowLogPayload_Type) Enum() *SlowLogPayload_Type {
	p := new(SlowLogPayload_Type)
	*p = x
	return p
}

func (x SlowLogPayload_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlowLogPayload_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_TooSlowLog_proto_enumTypes[0].Descriptor()
}

func (SlowLogPayload_Type) Type() protoreflect.EnumType {
	return &file_TooSlowLog_proto_enumTypes[0]
}

func (x SlowLogPayload_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SlowLogPayload_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SlowLogPayload_Type(num)
	return nil
}

// Deprecated: Use SlowLogPayload_Type.Descriptor instead.
func (SlowLogPayload_Type) EnumDescriptor() ([]byte, []int) {
	return file_TooSlowLog_proto_rawDescGZIP(), []int{0, 0}
}

type SlowLogPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime         *int64               `protobuf:"varint,1,req,name=start_time,json=startTime" json:"start_time,omitempty"`
	ProcessingTime    *int32               `protobuf:"varint,2,req,name=processing_time,json=processingTime" json:"processing_time,omitempty"`
	QueueTime         *int32               `protobuf:"varint,3,req,name=queue_time,json=queueTime" json:"queue_time,omitempty"`
	ResponseSize      *int64               `protobuf:"varint,4,req,name=response_size,json=responseSize" json:"response_size,omitempty"`
	ClientAddress     *string              `protobuf:"bytes,5,req,name=client_address,json=clientAddress" json:"client_address,omitempty"`
	ServerClass       *string              `protobuf:"bytes,6,req,name=server_class,json=serverClass" json:"server_class,omitempty"`
	MethodName        *string              `protobuf:"bytes,7,req,name=method_name,json=methodName" json:"method_name,omitempty"`
	CallDetails       *string              `protobuf:"bytes,8,req,name=call_details,json=callDetails" json:"call_details,omitempty"`
	Param             *string              `protobuf:"bytes,9,opt,name=param" json:"param,omitempty"`
	UserName          *string              `protobuf:"bytes,10,req,name=user_name,json=userName" json:"user_name,omitempty"`
	RegionName        *string              `protobuf:"bytes,11,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	MultiGets         *int32               `protobuf:"varint,12,opt,name=multi_gets,json=multiGets,def=0" json:"multi_gets,omitempty"`
	MultiMutations    *int32               `protobuf:"varint,13,opt,name=multi_mutations,json=multiMutations,def=0" json:"multi_mutations,omitempty"`
	MultiServiceCalls *int32               `protobuf:"varint,14,opt,name=multi_service_calls,json=multiServiceCalls,def=0" json:"multi_service_calls,omitempty"`
	Type              *SlowLogPayload_Type `protobuf:"varint,15,req,name=type,enum=pb.SlowLogPayload_Type" json:"type,omitempty"`
}

// Default values for SlowLogPayload fields.
const (
	Default_SlowLogPayload_MultiGets         = int32(0)
	Default_SlowLogPayload_MultiMutations    = int32(0)
	Default_SlowLogPayload_MultiServiceCalls = int32(0)
)

func (x *SlowLogPayload) Reset() {
	*x = SlowLogPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TooSlowLog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowLogPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowLogPayload) ProtoMessage() {}

func (x *SlowLogPayload) ProtoReflect() protoreflect.Message {
	mi := &file_TooSlowLog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowLogPayload.ProtoReflect.Descriptor instead.
func (*SlowLogPayload) Descriptor() ([]byte, []int) {
	return file_TooSlowLog_proto_rawDescGZIP(), []int{0}
}

func (x *SlowLogPayload) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *SlowLogPayload) GetProcessingTime() int32 {
	if x != nil && x.ProcessingTime != nil {
		return *x.ProcessingTime
	}
	return 0
}

func (x *SlowLogPayload) GetQueueTime() int32 {
	if x != nil && x.QueueTime != nil {
		return *x.QueueTime
	}
	return 0
}

func (x *SlowLogPayload) GetResponseSize() int64 {
	if x != nil && x.ResponseSize != nil {
		return *x.ResponseSize
	}
	return 0
}

func (x *SlowLogPayload) GetClientAddress() string {
	if x != nil && x.ClientAddress != nil {
		return *x.ClientAddress
	}
	return ""
}

func (x *SlowLogPayload) GetServerClass() string {
	if x != nil && x.ServerClass != nil {
		return *x.ServerClass
	}
	return ""
}

func (x *SlowLogPayload) GetMethodName() string {
	if x != nil && x.MethodName != nil {
		return *x.MethodName
	}
	return ""
}

func (x *SlowLogPayload) GetCallDetails() string {
	if x != nil && x.CallDetails != nil {
		return *x.CallDetails
	}
	return ""
}

func (x *SlowLogPayload) GetParam() string {
	if x != nil && x.Param != nil {
		return *x.Param
	}
	return ""
}

func (x *SlowLogPayload) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *SlowLogPayload) GetRegionName() string {
	if x != nil && x.RegionName != nil {
		return *x.RegionName
	}
	return ""
}

func (x *SlowLogPayload) GetMultiGets() int32 {
	if x != nil && x.MultiGets != nil {
		return *x.MultiGets
	}
	return Default_SlowLogPayload_MultiGets
}

func (x *SlowLogPayload) GetMultiMutations() int32 {
	if x != nil && x.MultiMutations != nil {
		return *x.MultiMutations
	}
	return Default_SlowLogPayload_MultiMutations
}

func (x *SlowLogPayload) GetMultiServiceCalls() int32 {
	if x != nil && x.MultiServiceCalls != nil {
		return *x.MultiServiceCalls
	}
	return Default_SlowLogPayload_MultiServiceCalls
}

func (x *SlowLogPayload) GetType() SlowLogPayload_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SlowLogPayload_SLOW_LOG
}

var File_TooSlowLog_proto protoreflect.FileDescriptor

var file_TooSlowLog_proto_rawDesc = []byte{
	0x0a, 0x10, 0x54, 0x6f, 0x6f, 0x53, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xda, 0x04, 0x0a, 0x0e, 0x53, 0x6c, 0x6f, 0x77, 0x4c,
	0x6f, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x06, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x5f, 0x67, 0x65, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x09,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x47, 0x65, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x0f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x5f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x75, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x31, 0x0a, 0x13, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x11, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x0f, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x4c, 0x4f, 0x57, 0x5f, 0x4c, 0x4f, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c,
	0x41, 0x52, 0x47, 0x45, 0x5f, 0x4c, 0x4f, 0x47, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c,
	0x4c, 0x10, 0x02, 0x42, 0x44, 0x0a, 0x31, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73,
	0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0a, 0x54, 0x6f, 0x6f, 0x53, 0x6c, 0x6f,
	0x77, 0x4c, 0x6f, 0x67, 0x48, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_TooSlowLog_proto_rawDescOnce sync.Once
	file_TooSlowLog_proto_rawDescData = file_TooSlowLog_proto_rawDesc
)

func file_TooSlowLog_proto_rawDescGZIP() []byte {
	file_TooSlowLog_proto_rawDescOnce.Do(func() {
		file_TooSlowLog_proto_rawDescData = protoimpl.X.CompressGZIP(file_TooSlowLog_proto_rawDescData)
	})
	return file_TooSlowLog_proto_rawDescData
}

var file_TooSlowLog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TooSlowLog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TooSlowLog_proto_goTypes = []interface{}{
	(SlowLogPayload_Type)(0), // 0: pb.SlowLogPayload.Type
	(*SlowLogPayload)(nil),   // 1: pb.SlowLogPayload
}
var file_TooSlowLog_proto_depIdxs = []int32{
	0, // 0: pb.SlowLogPayload.type:type_name -> pb.SlowLogPayload.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TooSlowLog_proto_init() }
func file_TooSlowLog_proto_init() {
	if File_TooSlowLog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TooSlowLog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowLogPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TooSlowLog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TooSlowLog_proto_goTypes,
		DependencyIndexes: file_TooSlowLog_proto_depIdxs,
		EnumInfos:         file_TooSlowLog_proto_enumTypes,
		MessageInfos:      file_TooSlowLog_proto_msgTypes,
	}.Build()
	File_TooSlowLog_proto = out.File
	file_TooSlowLog_proto_rawDesc = nil
	file_TooSlowLog_proto_goTypes = nil
	file_TooSlowLog_proto_depIdxs = nil
}
